elements = {
    ---[[ MEM ]]---
    {
        kind = 'line',
        from = {x = 56, y = 70},
        to = {x = 466, y = 70},
        alpha = 1,
        thickness = 2,
        color = 0x59aa49,
    },
    {
        kind = 'line',
        from = {x = 466, y = 60},
        to = {x = 466, y = 70},
        alpha = 1,
        thickness = 2,
        color = 0x59aa49,
    },
    {
        kind = 'bar_graph',
        conky_value = 'memperc',
        from = {x = 56, y = 70},
        to = {x = 56, y = 1606},
        bar_thickness = 2,
        bar_color = 0x59aa49,
        background_thickness = 2,
        background_alpha = .3,
        background_color = 0x59aa49,
        change_color_on_critical = false,
    },

    ---[[ CPU ]] ---
    {
        kind = 'line',
        from = {x = 4, y = 1540},
        to = {x = 26, y = 1540},
        alpha = .3,
        thickness = 2,
        color = 0xff79c6,
    },
    {
        kind = 'line',
        from = {x = 26, y = 20},
        to = {x = 106, y = 20},
        alpha = 1,
        thickness = 2,
        color = 0xff79c6,
    },
    {
        kind = 'line',
        from = {x = 106, y = 20},
        to = {x = 106, y = 30},
        alpha = 1,
        thickness = 2,
        color = 0xff79c6,
    },
    {
        kind = 'bar_graph',
        conky_value = 'cpu',
        from = {x = 26, y = 20},
        to = {x = 26, y = 1540},
        bar_thickness = 2,
        bar_color = 0xff79c6,
        background_thickness = 2,
        background_alpha = .3,
        background_color = 0xff79c6,
        change_color_on_critical = false,
    },

    ---[[ NET DOWN ]]--
    {
        kind = 'line',
        from = {x = 3835, y = 20},
        to = {x = 3069, y = 20},
        alpha = 1,
        thickness = 4,
        color = 0x000000,
    },
    {
        kind = 'line',
        from = {x = 3069, y = 20},
        to = {x = 3069, y = 30},
        alpha = 1,
        thickness = 4,
        color = 0x000000,
    },
    {
        kind = 'bar_graph',
        conky_value = 'downspeedf enp3s0',
        from = {x = 3835, y = 20},
        to = {x = 3835, y = 1606},
        bar_thickness = 4,
        bar_color = 0x000000,
        bar_alpha = 1,
        background_thickness = 4,
        background_alpha = .3,
        background_color = 0x000000,
        change_color_on_critical = false,
    },

    ---[[ NET UP ]]---
    {
        kind = 'line',
        from = {x = 3825, y = 70},
        to = {x = 3021, y = 70},
        alpha = 1,
        thickness = 4,
        color = 0x000000,
    },
    {
        kind = 'line',
        from = {x = 3021, y = 60},
        to = {x = 3021, y = 70},
        alpha = 1,
        thickness = 4,
        color = 0x000000,
    },
    {
        kind = 'bar_graph',
        conky_value = 'upspeedf enp3s0',
        from = {x = 3825, y = 70},
        to = {x = 3825, y = 1606},
        bar_thickness = 4,
        bar_color = 0x000000,
        bar_alpha = 1,
        background_thickness = 4,
        background_alpha = .3,
        background_color = 0x000000,
        change_color_on_critical = false,
    },

    --[[ BOTTOM LINES]] --
    -- RIGHT
    {
        kind = 'line',
        from = {x = 2743, y = 1606},
        to = {x = 2743, y = 1564},
        alpha = 1,
        thickness = 6,
        color = 0x000000,
    },
    {
        kind = 'line',
        from = {x = 2693, y = 1564},
        to = {x = 2746, y = 1564},
        alpha = 1,
        thickness = 6,
        color = 0x000000,
    },

    -- LEFT
    {
        kind = 'line',
        from = {x = 1107, y = 1606},
        to = {x = 1107, y = 1564},
        alpha = 1,
        thickness = 6,
        color = 0x000000,
    },
    {
        kind = 'line',
        from = {x = 1104, y = 1564},
        to = {x = 1157, y = 1564},
        alpha = 1,
        thickness = 6,
        color = 0x000000,
    },
};
