#!/bin/bash

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null
do
    sleep 1
done

PRIMARY_MONITOR=$(xrandr -q | grep primary | awk '{print $1}')

MONITOR=${PRIMARY_MONITOR} polybar stats 2>/dev/null & disown
MONITOR=${PRIMARY_MONITOR} polybar media 2>/dev/null & disown
MONITOR=${PRIMARY_MONITOR} polybar status 2>/dev/null & disown
MONITOR=${PRIMARY_MONITOR} polybar calendar 2>/dev/null & disown


while ! xdo lower -N Polybar >/dev/null
do
    sleep 1
done
