#!/bin/bash

killall -q conky
while pgrep -u $UID -x conky >/dev/null
do
    sleep 1
    killall -9 -q conky
done

while ! pgrep -u $UID -x polybar >/dev/null
do
    sleep 0.5
done

pushd ~/.config/conky
conky & disown
popd

while ! xdo lower -N Conky >/dev/null
do
    sleep 1
done
