#!/usr/bin/env bash

set -x

# Install Homebrew
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Install common utils
brew install \
    glibc \
    gcc \
    zsh \
    yadm \
    neovim \
    tmux \
    bat \
    ripgrep \
    zoxide \
    entr \
    fd \
    gpg \
    fzf \
    eza \
    diff-so-fancy \
    kubecolor

# Set ZSH as default shell
sudo chsh -s /home/linuxbrew/.linuxbrew/bin/zsh "${USER}"

env

# Clone dotfiles
yadm clone -f https://github.com/dangle/dotfiles
yadm reset --hard HEAD

if [[ "$(cat /proc/self/cgroup)" == "0::/" ]]; then
    yadm config local.class Container
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWRnIUgFh4FTnSCXySveVrOUCodTyigQNtlyupkIogX9XQADCIMUaFu3DjrTwFTlRiWIsJUWrpUajuZB7g8xs2tWsYZ2JomNENT1AJMu47g4zw0bUeqk35GJPNdLDM/QONTQMRMOF9VaHEN4S/WZjdtbscyOkMHvczVwyAHn62Db7KKLPK8Utci4qgSBPyzHmT7TSjzS81GRIegFum3/HRtyxQwyffK7D7HLctOTfcfThnfzi0i7aQDkrOSV2u7bpJLWfGqEVLOSv2lTpecwIr8uUWHx1+6akcJ0lIaJMOUWJbw0hU0rtUALHFlR0446NH2zE17kFDL+jdb/IEmypLv6Tdnjb/qJq0q3WURjOA8Oxco/aFtAyoCqt5XUgrcfHZeJzso7LY2yjXoNxlY8UtLdZ0dsCPslJi2fveCmxvUdih7CLdzWRbWRA3ZpxqlaGqAPxAP+E8W6BbZge5iXrpbNKR0lSPNswYAlIY1U1aOiGlYU6o4UdCD4Wi0IxaR+ZORk3LZFBna2/GGAJNQKK9cO5SYe7ii77DTaWJtN3S72E2n4GVVnZGoTw6VmhG0Lz4fmy+n7SpZqzGp1yPJc8GDQTaHTFbW3SkrO2s7dbK+8V72PLRTR17+ON/mWwS/EEHZazprLheFdIP3EABIouRR0d09KZvXmdbtpam1xc6OQ== melissa.nuno@gmail.com" > ~/.ssh/authorized_keys
fi

yadm alt

# Install vim-plug and plugins
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim +PlugInstall +UpdateRemotePlugins +qall
