#!/usr/bin/env bash

set -xe

# Install common utils on Debian-based distros
if command -v /usr/bin/apt-get &>/dev/null; then
  sudo apt-get update
  sudo apt-get install -y \
    zsh \
    yadm \
    neovim \
    tmux \
    bat \
    kitty-terminfo
fi

# Install common utils on Arch-based distros
if command -v /usr/bin/pacman &>/dev/null; then
    sudo pacman -Sy --noconfirm \
        python-pynvim \
        zsh \
        yadm \
        neovim \
        tmux \
        bat \
        kitty-terminfo
fi

# Install kubecolor if go exists
if command -v go &>/dev/null; then
  go install github.com/dty1er/kubecolor/cmd/kubecolor@latest
fi

# Set ZSH as default shell
chsh -s /usr/bin/zsh

# Clone dotfiles
yadm clone -f https://github.com/dangle/dotfiles

# Install vim-plug and plugins
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim +PlugInstall +UpdateRemotePlugins +qall

# Install diff-so-pretty
mkdir -p ~/bin || true
wget -P ~/bin https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
chmod +x ~/bin/diff-so-fancy
